package rahulArora;

import java.time.Duration;

import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.w3c.dom.html.HTMLTitleElement;

import io.github.bonigarcia.wdm.WebDriverManager;

public class DrowBorder {
	
	public static void main(String[] args) {
		
		WebDriverManager.chromedriver().setup();
		WebDriver driver=new ChromeDriver();
		driver.manage().window().maximize();
		WebDriverWait wait=new WebDriverWait(driver, Duration.ofSeconds(8));
		
		driver.get("https://en-gb.facebook.com/login/");
//		WebElement border=driver.findElement(By.xpath("/html/body/div[1]/h1/span"));
		
		
		JavascriptExecutor js=(JavascriptExecutor)driver;
		WebElement border=driver.findElement(By.id("email"));
		WebElement password=driver.findElement(By.name("pass"));
//		js.executeScript("argument[0].style.border='3px solid red'", border);
//		js.executeScript("document.getElementById('email').setAttribute('style','border:3px solid red;background:yellow')");
//		js.executeScript("document.getElementById('pass').setAttribute('style','border:3px solid red;background:yellow')");
//		js.executeScript("arguments[0].setAttribute('style','border:3px solid red;background:yellow')",border);
		js.executeScript("arguments[0].style.background='yellow'", border);
		js.executeScript("arguments[0].style.border='3px solid red'", password);
		String title1=js.executeScript("return document.title;").toString();
		System.out.println(title1);
		WebElement log=driver.findElement(By.name("login"));
		js.executeScript("arguments[0].click();",log);
		js.executeScript("alert('This is generated by me')");
		driver.switchTo().alert().accept();
		js.executeScript("history.go(0)");
		
		driver.get("https://www.wikipedia.org/");
		WebElement link=driver.findElement(By.xpath("/html/body/div[7]/div[3]/div[12]/a/div[2]/span[2]"));
		js.executeScript("arguments[0].scrollIntoView(true);",link);
		
		
		
		
		
	}

}

